<?php
$categorieslib = array(
'Adult' => array('webcam','xxx','sex','sexy','adult','porn'),
'Business' => array('global','gmbh','gold','group','holdings','immo','inc','industries','insurance','insure','international','investments','ventures','versicherung','net','capital','car','career','careers','cars','cash','ceo','cfa','cfd','claims','cleaning','co','cocom','company','consulting','corp','cpa','credit','creditcard','lease','lifeinsurance','limited','llc','llp','loan','loans','ltd','ltda','management','market','marketing','markets','mobi','money','mortgage','sale','sarl','spreadbetting','srl','tax','trade','trading','trust','dealer','enterprises','exchange','finance','financial','forex','foundation','fund','associates','auction','auto','autos','bank','banque','bargains','bid','biz','bizki','bizpl','boutique','broker','business','buy','partners','pay'),
'Culture' => array('ninja','org','charity','church','club','community'),
'Education' => array('health','healthcare','institute','university','cancerresearch','career','careers','college','courses','law','lawyer','loan','loans','management','marketing','mba','music','scholarships','school','schule','science','shiksha','study','training','degree','education','engineer','engineering','foundation','academy','art','photography','physio'),
'Food' => array('vin','vodka','wine','organic','cafe','catering','coffee','cooking','kitchen','kosher','menu','eat','farm','fish','food','bar','beer','pizza','pub','recipes','rest','restaurant'),
'Identity' => array('gal','gay','halal','hiphop','ink','ismaili','jetzt','uno','wedding','yoga','name','ninja','organic','cam','church','kid','kids','kim','kiwi','kosher','lat','latino','lgbt','lifestyle','luxe','luxury','me','men','moda','moe','mom','scot','shia','singles','surf','swiss','tattoo','dad','democrat','diet','dog','eco','faith','family','fashion','fit','fitness','arab','baby','beauty','bible','black','bzh','republican','rich','rocks'),
'Geographic' => array('gal','gent','hamburg','helsinki','international','ist','istanbul','joburg','vegas','vlaanderen','wales','wien','yokohama','zuerich','nagoya','nrw','nyc','okinawa','osaka','capetown','city','cologne','cymru','koeln','kyoto','london','madrid','melbourne','miami','moscow','saarland','scot','stockholm','sydney','taipei','tirol','tokyo','dubai','durban','eu','eucom','eus','abudhabi','africa','alsace','amsterdam','aquitaine','arab','asia','barcelona','bayern','berlin','boston','brussels','budapest','bzh','paris','persiangulf','quebec','ruhr','ryukyu'),
'Entertainment' => array('gallery','game','games','casino','movie','show','theater','theatre','dating','events','fun','art','bingo','play'),
'Professions' => array('healthcare','jobs','jurpro','vet','ceo','cfa','coach','consulting','contractors','cpa','cpapro','law','lawpro','lawyer','legal','makeup','med','medpro','dentist','dev','doctor','engineer','engineering','engpro','expert','florist','abogado','aaapro','acapro','accountant','accountants','actor','acctpro','archi','architect','associates','attorney','author','avocatpro','barpro','broker','builders','phd','physio','plumbing','pro','realtor','rechtpro'),
'Real Estate' => array('haus','home','homes','house','immo','immobilien','villas','casa','condos','construction','contractors','land','lease','maison','mls','mortgage','estate','farm','forsale','agency','apartments','place','properties','property','realestate','realtor','realty','rent','rentals'),
'Shopping' => array('games','gift','gifts','gold','gratis','grocery','guitars','health','holiday','hotel','hoteles','hotels','jewelry','vacations','viajes','watch','wedding','yachts','camera','car','cards','cars','cheap','christmas','clothing','compare','coupon','coupons','cruise','cruises','kaufen','lotto','luxe','luxe','luxury','luxury','makeup','market','motorcycles','sale','shoes','shop','shopping','spa','store','style','supplies','tickets','tienda','tires','toys','deal','deals','delivery','diamonds','direct','directory','discount','equipment','exchange','express','fashion','flights','florist','flowers','furniture','art','auction','audio','auto','autos','baby','bargains','beauty','bid','bike','blackfriday','boats','book','boutique','buy','plus','promo'),
'Fitness' => array('game','games','golf','hockey','horse','yachts','yoga','club','coach','cricket','live','ski','soccer','sport','surf','team','tennis','training','dance','events','fan','fans','fishing','fitness','football','futbol','baseball','basketball','bike','boats','racing','rodeo','rugby','run'),
'Technology' => array('hangout','host','hosting','ing','io','it','juegos','video','web','webcam','website','wiki','xyz','net','network','nu','onl','online','call','cam','camera','chat','click','cloud','co','codes','computer','kaufen','link','lol','mail','media','mobi','mobi','mobile','search','secure','site','social','software','stream','support','tech','technology','tube','data','date','dating','dev','digital','domains','download','email','app','blog','box','phone'),
'Travel' => array('guide','holiday','hotel','hoteles','hotels','vacations','viajes','villas','voyage','cab','camp','casa','cruise','cruises','limo','map','taxi','tickets','tours','travel','flights','fly','aero','boats','reise','reisen'),
'Others' => array('garden','gift','gifts','gives','giving','gold','green','gripe','guide','guitars','guru','hair','hangout','healthcare','help','here','hiv','holiday','horse','hot','hotel','hoteles','hotels','how','ing','ink','institute','jewelry','juegos','vote','voting','voto','voyage','watches','weather','win','work','works','world','wow','ws','wtf','yachts','you','zip','zone','new','nexus','ngo','now','one','onl','open','cab','cal','call','camp','cancerresearch','cards','center','channel','charity','club','coat','codes','community','compare','contact','cool','cruise','cruises','kid','kids','kinder','life','like','link','live','living','love','map','meet','meme','memorial','moto','motorcycles','safe','safety','salon','save','science','security','services','shoes','skin','social','solar','solutions','soy','spa','space','spot','storage','studio','sucks','support','systems','talk','tattoo','team','tickets','tips','today','top','tours','town','toys','trade','trust','tube','date','day','dds','delivery','democrat','design','directory','diy','docs','dot','drive','earth','eco','energy','esq','exchange','expert','exposed','fail','fan','fans','feedback','final','fish','flights','flowers','fly','foo','forum','free','furniture','fyi','associates','best','bet','bible','bio','blue','bom','boo','book','box','buzz','page','pars','party','pet','phone','pid','ping','pink','poker','prof','promo','protection','pub','qpon','red','rehab','reise','reisen','report','republican','review','reviews','rip','rodeo','rsvp'),
);
?>
